name: Tests

on:
  schedule:
    - cron: '0 0 * * SUN'
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validations:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            .npm
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git checkout ${{ env.BRANCH }}

      - uses: actions/setup-node@v3
        with:
          node-version: '*'
          check-latest: true

      - run: |
          python -m pip install --upgrade pip
          npm ci --cache .npm --prefer-offline
          npm install --global npm
          npm install

      - name: prettier
        run: npx prettier . --check

      - name: eslint
        run: npx eslint --color .

      - name: Build dist/ files
        run: npm run build

      - name: Run Tests
        run: npm run test
